# Generated by Django 5.2.5 on 2025-08-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=255, null=True)),
                ('session_created_at', models.DateTimeField(auto_now_add=True)),
                ('session_expires_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
