# Generated by Django 5.2.5 on 2025-08-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_customer', '0002_sessioninfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessioninfo',
            name='name',
            field=models.CharField(default='MMTC', max_length=255),
            preserve_default=False,
        ),
    ]
