class ExternalAPI:
    SESSION_COOKIE_NAME = 'sessionId'
    EXTERNAL_APIS = {
        'BASE_URL': 'https://cemuat.mmtcpamp.com',
        'AUTH_ENDPOINT': '/security/login',
        'CREATE_PROFILE_ENDPOINT': '/customer/createProfile',
        'CUSTOMER_CREATE_PROFILE': '/customer/createProfile',
        'UPDATE_PROFILE_ENDPOINT': '/customer/updateProfile',
        'CUSTOMER_UPDATE_PROFILE': '/customer/updateProfile',
        'PORTFOLIO_ENDPOINT': '/customer/getPortfolio',
        'GET_PROFILE_ENDPOINT': '/oat/getProfile',
        'CUSTOMER_PORTFOLIO': '/oat/getPortfolio',
        'CUSTOMER_GET_PROFILE': '/customer/getProfile',
        'ACTIVATE_CUSTOMER_ENDPOINT': '/customer/activate',
        'DEACTIVATE_CUSTOMER_ENDPOINT': '/customer/inactivate',
        'VALIDATE_CUSTOMER_ENDPOINT': '/customer/validate',
        'INVALIDATE_CUSTOMER_ENDPOINT': '/customer/invalidate',
        'GOLD_PRICE_ENDPOINT': '/PRICE/XAU/INR',
        'SILVER_PRICE_ENDPOINT': '/PRICE/XAG/INR',
        'ESTIMATE_ENDPOINT': '/pvt/getNonExecutableQuote',
        'TRADE_BUY_ENDPOINT': '/trade/getQuoteBuy',
        'TRADE_VALIDATE_ENDPOINT_PG': '/trade/validateQuotePartnerPg',
        "TRADE_GET_SELL_QUOTE": "/trade/getQuoteSell",
            #"TRADE_EXECUTE_ORDER": "/trade/executeOrderPartnerPg",
        "TRADE_EXECUTE_SELL": "/trade/executeOrderPartnerPg",
            #'TRADE_SELL_ENDPOINT': '/pvt/getNonExecutableQuote',
            #'TRADE_TRANSFER_ENDPOINT': '/pvt/getNonExecutableQuote',
        "TRADE_EXECUTE_ORDER_PARTNER_PG": "/trade/executeOrderPartnerPg",
        'CREATE_CUSTOMER_ENDPOINT': '/customer/createProfile',
        }
