# Generated by Django 5.2.5 on 2025-09-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_profile_addressproofid_profile_addressprooftype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dgcustomerRefNo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
