# Generated by Django 5.2.5 on 2025-09-04 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0003_profile_dgcustomerrefno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='billing_address',
            new_name='billingAddress',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='delivery_address',
            new_name='deliveryAddress',
        ),
    ]
