# Generated by Django 5.2.5 on 2025-09-06 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0005_alter_profile_billingaddress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='billingAddress',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='deliveryAddress',
            field=models.TextField(),
        ),
    ]
