# Generated by Django 5.2.5 on 2025-12-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0008_alter_profile_billingaddress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='billingAddressId',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
