# Generated by Django 6.0 on 2025-12-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0009_profile_billingaddressid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='kycStatus',
            field=models.CharField(default='I', max_length=1),
        ),
    ]
