# Generated by Django 6.0 on 2025-12-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0010_alter_profile_kycstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='deliveryAddressId',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
