# Generated by Django 6.0 on 2025-12-22 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sell', '0002_remove_sellorder_listing_remove_sellorder_buyer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellquote',
            name='transaction_ref_no',
            field=models.CharField(default='legacy', max_length=64),
            preserve_default=False,
        ),
    ]
