# Generated by Django 6.0 on 2025-12-22 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sell', '0003_sellquote_transaction_ref_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellquote',
            name='transaction_ref_no',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
