# Generated by Django 6.0 on 2025-12-18 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0003_emailverification_phoneverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 18, 16, 31, 10, 194500, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='phoneverification',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 18, 16, 31, 10, 195057, tzinfo=datetime.timezone.utc)),
        ),
    ]
