# Generated by Django 6.0 on 2025-12-22 09:47

import app_login.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0004_alter_emailverification_valid_until_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverification',
            name='valid_until',
            field=models.DateTimeField(default=app_login.models.email_token_expiry),
        ),
        migrations.AlterField(
            model_name='phoneverification',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 22, 9, 52, 9, 233129, tzinfo=datetime.timezone.utc)),
        ),
    ]
