# Generated by Django 6.0 on 2025-12-22 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_login', '0005_alter_emailverification_valid_until_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneverification',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 22, 12, 17, 7, 663076, tzinfo=datetime.timezone.utc)),
        ),
    ]
