# Generated by Django 5.2.5 on 2025-10-04 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_trade', '0002_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradebuy',
            name='createdAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tradebuy',
            name='quoteValidityTime',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
