# Generated by Django 5.2.5 on 2025-12-29 09:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_trade', '0007_quote_unitpriceamt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='calculationType',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='quote',
            name='createdAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='currencyPair',
            field=models.CharField(default='XAU/INR', max_length=10),
        ),
        migrations.AlterField(
            model_name='quote',
            name='customerRefNo',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='preTaxAmt',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quantity',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=16),
        ),
        migrations.AlterField(
            model_name='quote',
            name='quoteId',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='tax1Amt',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16),
        ),
        migrations.AlterField(
            model_name='quote',
            name='tax1Perc',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='quote',
            name='tax2Amt',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16),
        ),
        migrations.AlterField(
            model_name='quote',
            name='tax2Perc',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='quote',
            name='tax3Amt',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16),
        ),
        migrations.AlterField(
            model_name='quote',
            name='tax3Perc',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='quote',
            name='taxAmount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16),
        ),
        migrations.AlterField(
            model_name='quote',
            name='totalAmt',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16),
        ),
        migrations.AlterField(
            model_name='quote',
            name='transactionOrderID',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='unitPriceAmt',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=16),
        ),
    ]
