# Generated by Django 5.2.5 on 2025-09-14 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0001_initial'),
        ('app_user', '0008_alter_profile_billingaddress_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_pair', models.CharField(max_length=20)),
                ('bal_quantity', models.DecimalField(decimal_places=4, max_digits=20)),
                ('blocked_quantity', models.DecimalField(decimal_places=4, max_digits=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='app_user.profile')),
            ],
        ),
    ]
