# Generated by Django 5.2.5 on 2025-09-14 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0002_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
