# Generated by Django 5.2.5 on 2025-09-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0003_balance_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='customerName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
