# Generated by Django 5.2.5 on 2025-09-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0004_balance_customername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='customer',
        ),
        migrations.AddField(
            model_name='balance',
            name='custRefNo',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='balance',
            name='kyc_status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
