# Generated by Django 5.2.5 on 2025-12-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0005_remove_balance_customer_balance_custrefno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='balance_as_of',
            field=models.DateTimeField(null=True),
        ),
    ]
