# Generated by Django 6.0 on 2025-12-25 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0007_holding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerRefNo', models.CharField(max_length=100)),
                ('transactionType', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=10)),
                ('currencyPair', models.CharField(max_length=20)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=20)),
                ('totalAmt', models.DecimalField(decimal_places=2, max_digits=20)),
                ('orderId', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(default='EXECUTED', max_length=20)),
                ('transactionDate', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
